# Generated by Django 5.1.4 on 2024-12-21 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseAmenities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amenities.amenity')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
